name: Seed MongoDB
on:
  workflow_dispatch: # Allows you to run the workflow manually from the GitHub UI
jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      working-directory: ./backend # Set working directory to install requirements from here
      run: pip install -r requirements.txt # Or use `pip install pymongo python-dotenv motor`

    - name: Run seeding script
      run: python seed_data.py
      working-directory: ./backend # Run the script from within the backend folder
      env:
        MONGODB_URI: mongodb+srv://ai-master-dipesh:dev19patel@portfolio-dipesh.c70uwfb.mongodb.net/portfolio_database?retryWrites=true&w=majority&appName=portfolio-dipesh # Pass the secret as an environment variable
